
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class PrograMenu extends javax.swing.JFrame {

    /**
     * Creates new form PrograMenu
     */
    public PrograMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbEspresso = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbAmericano = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        txtJumlah2 = new javax.swing.JTextField();
        txtJumlah3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cbLatte = new javax.swing.JCheckBox();
        cbCappuccino = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        txtJumlah4 = new javax.swing.JTextField();
        cbFlat = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        txtJumlah5 = new javax.swing.JTextField();
        cbMachiatto = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        txtJumlah6 = new javax.swing.JTextField();
        txtJumlah1 = new javax.swing.JTextField();
        cbMatcha = new javax.swing.JCheckBox();
        cbChocolate = new javax.swing.JCheckBox();
        cbRed = new javax.swing.JCheckBox();
        cbCaramel = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJumlah7 = new javax.swing.JTextField();
        txtJumlah8 = new javax.swing.JTextField();
        txtJumlah9 = new javax.swing.JTextField();
        txtJumlah10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTagihan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPesanan = new javax.swing.JTextArea();
        bPesan = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Coffee");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Harga");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Jumlah Beli");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Non Coffee");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Harga");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Jumlah Beli");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("MENU COFFEE SHOP");

        cbEspresso.setText("Espresso");
        cbEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspressoActionPerformed(evt);
            }
        });

        jLabel1.setText("Rp. 20.000");

        cbAmericano.setText("Americano");

        jLabel21.setText("Rp. 25.000");

        jLabel22.setText("Rp. 23.000");

        cbLatte.setText("Latte");

        cbCappuccino.setText("Cappuccino");

        jLabel23.setText("Rp. 25.000");

        cbFlat.setText("Flat White");

        jLabel24.setText("Rp. 25.000");

        txtJumlah5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlah5ActionPerformed(evt);
            }
        });

        cbMachiatto.setText("Machiatto");

        jLabel25.setText("Rp. 25.000");

        txtJumlah6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlah6ActionPerformed(evt);
            }
        });

        txtJumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlah1ActionPerformed(evt);
            }
        });

        cbMatcha.setText("Matcha");

        cbChocolate.setText("Chocolate");

        cbRed.setText("Red Velvet");

        cbCaramel.setText("Caramel");

        jLabel4.setText("Rp. 20.000");

        jLabel6.setText("Rp. 23.000");

        jLabel7.setText("Rp. 25.000");

        jLabel8.setText("Rp. 25.000");

        txtJumlah7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlah7ActionPerformed(evt);
            }
        });

        txtJumlah8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlah8ActionPerformed(evt);
            }
        });

        txtJumlah9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlah9ActionPerformed(evt);
            }
        });

        txtJumlah10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlah10ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Jumlah Tagihan");

        txtTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTagihanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Uang Bayar");

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBayarKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Uang Kembali");

        txtKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Menu Yang Di Pesan :");

        taPesanan.setColumns(20);
        taPesanan.setRows(5);
        jScrollPane1.setViewportView(taPesanan);

        bPesan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bPesan.setText("Pesan");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("(Jika sudah tekan Enter)");

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbEspresso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLatte)
                            .addComponent(cbAmericano)
                            .addComponent(cbCappuccino)
                            .addComponent(cbFlat)
                            .addComponent(cbMachiatto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel21)
                            .addComponent(jLabel1)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtJumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbMatcha)
                                            .addComponent(cbRed)
                                            .addComponent(cbChocolate)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtJumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbCaramel))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                                .addComponent(jLabel13)))
                                        .addGap(11, 11, 11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJumlah10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJumlah9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtJumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtJumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(54, 54, 54)
                                            .addComponent(jLabel15))))
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(189, 189, 189))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtKembali))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(55, 55, 55)
                                .addComponent(jButton2)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel20)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEspresso)
                    .addComponent(jLabel1)
                    .addComponent(txtJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChocolate)
                    .addComponent(jLabel4)
                    .addComponent(txtJumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAmericano)
                    .addComponent(jLabel21)
                    .addComponent(txtJumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMatcha)
                    .addComponent(jLabel6)
                    .addComponent(txtJumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtJumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(cbRed)
                        .addComponent(jLabel7)
                        .addComponent(txtJumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbLatte))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCappuccino)
                    .addComponent(txtJumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtJumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbCaramel)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFlat)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(txtJumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMachiatto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(txtJumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(bPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlah5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlah5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlah5ActionPerformed

    private void txtJumlah6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlah6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlah6ActionPerformed

    private void txtJumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlah1ActionPerformed

    private void txtJumlah7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlah7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlah7ActionPerformed

    private void txtJumlah8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlah8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlah8ActionPerformed

    private void txtJumlah9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlah9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlah9ActionPerformed

    private void txtJumlah10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlah10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlah10ActionPerformed

    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int bayar = 0;
        if (cbEspresso.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah1.getText());
            int total;
            int harga=20000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbEspresso.getText()+"     Rp.20000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbAmericano.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah2.getText());
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbAmericano.getText()+"    Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbLatte.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah3.getText());
            int total;
            int harga=23000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbLatte.getText()+"    Rp.23000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbCappuccino.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah4.getText());
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbCappuccino.getText()+"   Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbFlat.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah5.getText());
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbFlat.getText()+"     Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbMachiatto.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah6.getText());
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbMachiatto.getText()+"    Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbChocolate.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah7.getText());
            int total;
            int harga=20000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbChocolate.getText()+"    Rp.20000"+" x "+jumlah+" = "+total+"\n";
        }
         if (cbMatcha.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah8.getText());
            int total;
            int harga=23000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbChocolate.getText()+"    Rp.23000"+" x "+jumlah+" = "+total+"\n";
        }
          if (cbRed.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah9.getText());
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbRed.getText()+"    Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
           if (cbCaramel.isSelected()){
            int jumlah=Integer.parseInt(txtJumlah10.getText());
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbCaramel.getText()+"   Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        taPesanan.setText(tampil+"==================================="+"\n"+"Total Bayar : "+bayar);
        txtTagihan.setText(Integer.toString(bayar));
    }//GEN-LAST:event_bPesanActionPerformed

    private void txtTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagihanActionPerformed

    private void txtBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int UangBayar = Integer.parseInt(txtBayar.getText());
            int TotalBayar = Integer.parseInt(txtTagihan.getText());
            if (UangBayar<TotalBayar){
                JOptionPane.showMessageDialog(null, "Uang yang Dibayarkan Tidak Cukup!");
            }
            else {
                txtKembali.setText(Integer.toString(UangBayar - TotalBayar));
            }
        }
    }//GEN-LAST:event_txtBayarKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               int x;
        x = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (x==JOptionPane.YES_NO_OPTION){
            dispose();
        }
        else{
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtJumlah1.setText("");
        txtJumlah2.setText("");
        txtJumlah3.setText("");
        txtJumlah4.setText("");
        txtJumlah5.setText("");
        txtJumlah6.setText("");
        txtJumlah7.setText("");
        txtJumlah8.setText("");
        txtJumlah9.setText("");
        txtJumlah10.setText("");
        taPesanan.setText("");
        txtBayar.setText("");
        txtTagihan.setText("");
        txtKembali.setText("");
        cbEspresso.setSelected(false);
        cbAmericano.setSelected(false);
        cbLatte.setSelected(false);
        cbCappuccino.setSelected(false);
        cbFlat.setSelected(false);
        cbMachiatto.setSelected(false);
        cbChocolate.setSelected(false);
        cbMatcha.setSelected(false);
        cbRed.setSelected(false);
        cbCaramel.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void cbEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspressoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrograMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrograMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrograMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrograMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrograMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPesan;
    private javax.swing.JCheckBox cbAmericano;
    private javax.swing.JCheckBox cbCappuccino;
    private javax.swing.JCheckBox cbCaramel;
    private javax.swing.JCheckBox cbChocolate;
    private javax.swing.JCheckBox cbEspresso;
    private javax.swing.JCheckBox cbFlat;
    private javax.swing.JCheckBox cbLatte;
    private javax.swing.JCheckBox cbMachiatto;
    private javax.swing.JCheckBox cbMatcha;
    private javax.swing.JCheckBox cbRed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taPesanan;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtJumlah1;
    private javax.swing.JTextField txtJumlah10;
    private javax.swing.JTextField txtJumlah2;
    private javax.swing.JTextField txtJumlah3;
    private javax.swing.JTextField txtJumlah4;
    private javax.swing.JTextField txtJumlah5;
    private javax.swing.JTextField txtJumlah6;
    private javax.swing.JTextField txtJumlah7;
    private javax.swing.JTextField txtJumlah8;
    private javax.swing.JTextField txtJumlah9;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtTagihan;
    // End of variables declaration//GEN-END:variables
}
